// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrvhqkilzxopesfmpjbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impydmhxa2lsenhvcGVzZm1wamJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNzg2MTEsImV4cCI6MjA1ODY1NDYxMX0.7A4Pg9sEhyAsqQ-gHH7HJgroZHj14AXRU9Ahdelknj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);